# Generated by Django 5.0.6 on 2024-06-16 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.IntegerField()),
                ('merchant', models.CharField(max_length=100)),
                ('Chequenumber', models.CharField(max_length=16)),
                ('Account_holder_name', models.CharField(max_length=100)),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
